---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_k3s/handlers/main.yml
# Description : main handler
# ------------------------------------------------------------------------------

- name: ctlabs_k3s.handlers.server.systemd.reload
  systemd:
    name          : "{{ ctlabs_k3s.defaults.service.server.name }}" 
    enabled       : true
    daemon_reload : true

- name: ctlabs_k3s.handlers.service.server.started
  service:
    name  : "{{ ctlabs_k3s.defaults.service.server.name }}"
    state : started

- name: ctlabs_k3s.handlers.control.systemd.reload
  systemd:
    name          : "{{ ctlabs_k3s.defaults.service.control.name }}"
    enabled       : true
    daemon_reload : true

- name: ctlabs_k3s.handlers.worker.systemd.reload
  systemd:
    name          : "{{ ctlabs_k3s.defaults.service.worker.name }}"
    enabled       : true
    daemon_reload : true
