---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_opencode/tasks/main.yml
# Description : main task file
# ------------------------------------------------------------------------------

- import_tasks: precheck.yml
  tags:
    - ctlabs_opencode
    - ctlabs_opencode.precheck
    - ctlabs_opencode.package
    - ctlabs_opencode.config
    - ctlabs_opencode.service

- import_tasks: package.yml
  tags:
    - ctlabs_opencode
    - ctlabs_opencode.package

- import_tasks: config.yml
  tags:
    - ctlabs_opencode
    - ctlabs_opencode.config

- import_tasks: service.yml
  tags:
    - ctlabs_opencode
    - ctlabs_opencode.service
