---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_opencode/tasks/precheck.yml
# Description : prechecks
# ------------------------------------------------------------------------------

- name: ctlabs_opencode.tasks.precheck
  block:
    - name: ctlabs_opencode.tasks.precheck.supported_os
      assert:
        that: ctg_os is in ctlabs_opencode.os
        fail_msg: "OS [{{ ctg_os }}] is not supported!"
  rescue:
    - name: ctlabs_opencode.tasks.precheck.skip.unsupported
      meta: end_host
