---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_opencode/tasks/service.yml
# Description : services
# ------------------------------------------------------------------------------
