---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_meilisearch/tasks/precheck.yml
# Description : prechecks
# ------------------------------------------------------------------------------

- name: ctlabs_meilisearch.tasks.precheck
  block:
    - name: ctlabs_meilisearch.tasks.precheck.os.supported
      assert:
        that     : ctg_os is in ctlabs_meilisearch.os
        fail_msg : "OS[{{ ctg_os }}] is not supported!"
  rescue:
    - name: ctlabs_meilisearch.tasks.precheck.skip.unsupported
      meta: end_host
