---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_postfix/tasks/dkim.yml
# Description : dkimpy-milter setup
# ------------------------------------------------------------------------------

- name: ctlabs_postfix.tasks.dkim.package.installed
  package:
    name  : "{{ item.name }}"
    state : present
  loop: "{{ ctlabs_postfix.defaults.dkim.pkgs }}"

- name: ctlabs_postfix.tasks.dkim.config.dir
  file:
    path  : "{{ ctlabs_postfix.defaults.dkim.config.dir }}"
    state : directory
    mode  : '0755'

- name: ctlabs_postfix.tasks.dkim.config.file
  template:
    src  : dkimpy-milter.conf.j2
    dest : "{{ ctlabs_postfix.defaults.dkim.config.dir }}/{{ ctlabs_postfix.defaults.dkim.config.file }}"
  notify: ctlabs_postfix.handlers.dkimpy_milter.restart

- name: ctlabs_postfix.tasks.dkim.keys.dir
  file:
    path  : "{{ ctlabs_postfix.defaults.dkim.keys.dir }}"
    state : directory
    mode  : '0700'

- name: ctlabs_postfix.tasks.dkim.keys.generate
  openssl_privatekey:
    path : "{{ ctlabs_postfix.defaults.dkim.keys.dir }}/{{ ctlabs_postfix_dkim_selector }}.key"
    size : "{{ ctlabs_postfix.defaults.dkim.keys.bits }}"
    mode : '0600'

- name: ctlabs_postfix.tasks.dkim.service.running
  service:
    name    : "{{ ctlabs_postfix.defaults.dkim.service.name }}"
    enabled : true
    state   : started
