---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_postfix/tasks/precheck.yml
# Description : tasks prechecks
# ------------------------------------------------------------------------------

- name: ctlabs_postfix.tasks.precheck
  block:
    - name: ctlabs_postfix.tasks.precheck.os.supported
      assert:
        that: ctg_os is in ctlabs_postfix.os
        fail_msg: "OS [{{ ctg_os }}] is not supported!"
  rescue:
    - name: ctlabs_postfix.tasks.precheck.skip.unsupported
      meta: end_host

- name: ctlabs_postfix.tasks.precheck.relayhost
  set_fact:
    ctlabs_postfix_relayhost: "{{ ctg_facts.ctlabs_postfix.relayhost | default('') }}"
