---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_kafka/tasks/config.yml
# Description : create default configuration user/directories
# ------------------------------------------------------------------------------


- name: ctlabs_kafka.tasks.config.server.main
  template:
    src : "{{ ctlabs_kafka.defaults.config.server.main.template }}"
    dest: "{{ ctlabs_kafka.defaults.config.dirs.main }}/{{ ctlabs_kafka.defaults.config.server.main.file }}"
  notify: ctlabs_kafka.handlers.service.restart

- name: ctlabs_kafka.tasks.config.server.auth
  template:
    src  : "{{ ctlabs_kafka.defaults.config.server.auth.template }}"
    dest : "{{ ctlabs_kafka.defaults.config.dirs.main }}/{{ ctlabs_kafka.defaults.config.server.auth.file }}"
  notify: ctlabs_kafka.handlers.service.kafka.restart

- name: ctlabs_kafka.tasks.config.server.auth.perms
  file:
    path: "{{ ctlabs_kafka.defaults.config.dirs.main }}/{{ ctlabs_kafka.defaults.config.server.auth.file }}"
    owner: "{{ ctlabs_kafka.defaults.service.user  }}"
    group: "{{ ctlabs_kafka.defaults.service.group }}"
    mode: '0400'
  notify: ctlabs_kafka.handlers.service.kafka.restart
