---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_openclaw/tasks/config.yml
# Description : configurations
# ------------------------------------------------------------------------------

- name: ctlabs_openclaw.tasks.package.group
  group:
    name   : "{{ ctlabs_openclaw.defaults.service.group }}"
    system : true

- name: ctlabs_openclaw.tasks.package.user
  user:
    name   : "{{ ctlabs_openclaw.defaults.service.user  }}"
    group  : "{{ ctlabs_openclaw.defaults.service.group }}"
    system : true

- name: ctlabs_openclaw.tasks.package.group.certs.member
  user:
    name  : "{{ ctlabs_openclaw.defaults.service.user   }}"
    group : "{{ ctlabs_openclaw.defaults.service.group  }}"
    groups: "{{ ctlabs_openclaw.defaults.service.groups }}"
    shell : /bin/bash

- name: ctlabs_openclaw.tasks.config.openclaw.dir
  file:
    path : "{{ ctlabs_openclaw.defaults.config.dir }}"
    state: directory
    owner: "{{ ctlabs_openclaw.defaults.service.user  }}"
    group: "{{ ctlabs_openclaw.defaults.service.group }}"
    mode : '0750'
    
- name: ctlabs_openclaw.tasks.config.openclaw.json
  template:
    src  : "{{ ctlabs_openclaw.defaults.config.template }}"
    dest : "{{ ctlabs_openclaw.defaults.config.file     }}"
    owner: "{{ ctlabs_openclaw.defaults.service.user    }}"
    group: "{{ ctlabs_openclaw.defaults.service.group   }}"

- name: ctlabs_openclaw.tasks.config.gateway.dir
  file:
    path : "{{ ctlabs_openclaw.defaults.config.dir }}/gateway"
    state: directory
    owner: "{{ ctlabs_openclaw.defaults.service.user    }}"
    group: "{{ ctlabs_openclaw.defaults.service.group   }}"
    mode : '0750'

#- name: ctlabs_openclaw.tasks.config.pairing.token
#  copy:
#    dest: "{{ ctlabs_openclaw.defaults.config.dir }}/gateway/config.json"
#    content: |
#      {
#        "pairing": {
#          "token"   : "{{ ctlabs_openclaw_pairing_token }}",
#          "enabled" : true
#        }
#      }
#    mode: '0600'


