---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_openclaw/tasks/package.yml
# Description : packages
# ------------------------------------------------------------------------------

- name: ctlabs_openclaw.tasks.package.debian.update.cache
  when: ctg_os_family == 'debian'
  apt:
    update_cache: true

- name: ctlabs_openclaw.tasks.package.pkgs.installed
  package:
    name  : "{{ item.name }}"
    state : present
  loop    : "{{ ctlabs_openclaw.defaults.pkgs[ctg_os_family] }}"
  register: result
  until   : result is success

- name: ctlabs_openclaw.tasks.package.openclaw.installed
  npm: 
    name  : openclaw
    state : latest
    global: true
