---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_openclaw/tasks/service.yml
# Description : services
# ------------------------------------------------------------------------------

- name: ctlabs_openclaw.tasks.service.openclaw.install
  template:
    src  : "{{ ctlabs_openclaw.defaults.service.template }}"
    dest : "{{ ctlabs_openclaw.defaults.service.file     }}"
  notify: ctlabs_openclaw.handlers.openclaw.service.restarted

- name: ctlabs_openclaw.tasks.service.openclaw.running
  service:
    name    : "{{ ctlabs_openclaw.defaults.service.name }}"
    state   : started
    enabled : true

- name: ctlabs_openclaw.tasks.service.openclaw.pairing.url
  command: openclaw dashboard --no-open
  register: pairing_url

- debug: "msg={{ pairing_url.stdout }}"

#- name: ctlabs_openclaw.tasks.service.openclaw.devices
#  command: openclaw devices list
#  register: device_list
#
#- debug: "msg={{ device_list.stdout }}"
