---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_openclaw/tasks/service.yml
# Description : services
# ------------------------------------------------------------------------------

- name: ctlabs_openclaw.tasks.service.openclaw.install
  template:
    src  : "{{ ctlabs_openclaw.defaults.service.template }}"
    dest : "{{ ctlabs_openclaw.defaults.service.file     }}"
  notify: ctlabs_openclaw.handlers.openclaw.service.restarted

- name: ctlabs_openclaw.tasks.service.openclaw.running
  service:
    name    : "{{ ctlabs_openclaw.defaults.service.name }}"
    state   : started
    enabled : true

- name: ctlabs_openclaw.tasks.service.openclaw.pairing.url
  command: openclaw dashboard --no-open
  register: pairing_url

- name: ctlabs_openclaw.tasks.service.openclaw.pairing.fact
  set_fact:
    pairing_url_clean: "{{ pairing_url.stdout | regex_search('(http[s]?://[^\\s]+)') }}"

- debug: "msg=Open this URL in your browser: {{ pairing_url_clean }}"
