---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_base/tasks/facts.yml
# Description : write local facts (Linux disks / Windows ctlabs.ps1)
# ------------------------------------------------------------------------------

#
# Linux
#
- name: ctlabs_base.tasks.facts.linux
  when: ctg_os_family in ['redhat', 'debian']
  block:
    - name: ctlabs_base.tasks.facts.linux.disks
      template:
        src  : "{{ ctlabs_base.defaults.config.local_facts.template }}"
        dest : "{{ ctlabs_base.defaults.config.local_facts.file     }}"
        mode : '0750'
        owner: root
        group: root

    - name: ctlabs_base.tasks.facts.linux.reread
      setup:

    - name: ctlabs_base.tasks.facts.linux.disks.set_fact
      set_fact:
        ctlabs_base_disks: "{{ ctg_facts.ctlabs_base_disks if ctg_facts.ctlabs_base_disks is defined else [] }}"

#
# Windows
#
- name: ctlabs_base.tasks.facts.windows
  when: ctg_os_family == 'windows'
  block:
    - name: ctlabs_base.tasks.facts.windows.facts_dir
      win_file:
        path  : "{{ ctg_facts_dir }}"
        state : directory

    - name: ctlabs_base.tasks.facts.windows.local_facts
      win_template:
        src  : "{{ item.template }}"
        dest : "{{ item.file     }}"
      loop: "{{ ctlabs_base.defaults.config.windows.local_facts }}"

    - name: ctlabs_base.tasks.facts.windows.reread
      setup:
        fact_path: "{{ ctg_facts_dir }}"

    - name: ctlabs_base.tasks.facts.windows.disks.set_fact
      set_fact:
        ctlabs_base_disks: "{{ ctg_facts.ctlabs_base_disks if ctg_facts.ctlabs_base_disks is defined else [] }}"
