---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_vault/handlers/main.yml
# Description : handlers
# ------------------------------------------------------------------------------

- name: ctlabs_vault.handlers.service.vault.restart
  service:
    name    : "{{ ctlabs_vault.defaults.service.server.name }}"
    enabled : true
    state   : restarted

- name: ctlabs_vault.handlers.service.vault.reload
  systemd:
    daemon_reload: true

- name: ctlabs_vault.handlers.service.agent.restart
  service:
    name    : "{{ ctlabs_vault.defaults.service.agent.name }}"
    enabled : true
    state   : restarted

- name: ctlabs_vault.handlers.service.proxy.restart
  service:
    name    : "{{ ctlabs_vault.defaults.service.proxy.name }}"
    enabled : true
    state   : restarted
