---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_dkim/meta/main.yml
# Description : role dependencies
# ------------------------------------------------------------------------------

dependencies:
  - role: ctlabs_postfix
