---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_opendkim/tasks/config.yml
# Description : configuration
# ------------------------------------------------------------------------------

- name: ctlabs_opendkim.tasks.config.dir
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ ctlabs_opendkim.defaults.service.user }}"
    group: "{{ ctlabs_opendkim.defaults.service.group }}"
  loop:
    - "{{ ctlabs_opendkim.defaults.config.dir }}"
    - "{{ ctlabs_opendkim.defaults.key.dir }}"
    - "{{ ctlabs_opendkim.defaults.key.dir }}/{{ ctlabs_opendkim_domain }}"

- name: ctlabs_opendkim.tasks.config.key.generate
  ansible.builtin.command: >
    opendkim-genkey -D {{ ctlabs_opendkim.defaults.key.dir }}/{{ ctlabs_opendkim_domain }}
    -d {{ ctlabs_opendkim_domain }}
    -s {{ ctlabs_opendkim_selector }}
    -a {{ ctlabs_opendkim.defaults.key.type }}
    -b {{ ctlabs_opendkim.defaults.key.length }}
  args:
    creates: "{{ ctlabs_opendkim.defaults.key.dir }}/{{ ctlabs_opendkim_domain }}/{{ ctlabs_opendkim_selector }}.private"
  notify: ctlabs_opendkim.handlers.service.restart

- name: ctlabs_opendkim.tasks.config.key.owner
  ansible.builtin.file:
    path: "{{ ctlabs_opendkim.defaults.key.dir }}/{{ ctlabs_opendkim_domain }}"
    state: directory
    recurse: true
    owner: "{{ ctlabs_opendkim.defaults.service.user }}"
    group: "{{ ctlabs_opendkim.defaults.service.group }}"

- name: ctlabs_opendkim.tasks.config.file
  template:
    src : "{{ ctlabs_opendkim.defaults.config.template }}"
    dest: "{{ ctlabs_opendkim.defaults.config.file }}"
  notify: ctlabs_opendkim.handlers.service.restart

- name: ctlabs_opendkim.tasks.config.files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ ctlabs_opendkim.defaults.config.dir }}/{{ item }}"
    owner: root
    group: "{{ ctlabs_opendkim.defaults.service.group }}"
    mode: '0640'
  loop: "{{ ctlabs_opendkim.defaults.config.files }}"
  notify: ctlabs_opendkim.handlers.service.restart

- name: ctlabs_opendkim.tasks.config.postfix_user
  ansible.builtin.user:
    name: postfix
    groups: "{{ ctlabs_opendkim.defaults.service.group }}"
    append: true
  notify: ctlabs_opendkim.handlers.service.postfix_reload
