---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_opendkim/tasks/config.yml
# Description : configuration
# ------------------------------------------------------------------------------

- name: ctlabs_opendkim.tasks.config.dir
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ ctlabs_opendkim.defaults.service.user }}"
    group: "{{ ctlabs_opendkim.defaults.service.group }}"
  loop:
    - "{{ ctlabs_opendkim.defaults.config.dir }}"
    - "{{ ctlabs_opendkim.defaults.key.dir }}"
    - "{{ ctlabs_opendkim.defaults.key.dir }}/{{ ctlabs_opendkim_domain }}"

- name: ctlabs_opendkim.tasks.config.key.generate
  community.crypto.openssl_privatekey:
    path: "{{ ctlabs_opendkim.defaults.key.dir }}/{{ ctlabs_opendkim_domain }}/{{ ctlabs_opendkim_selector }}.private"
    type: "{{ ctlabs_opendkim_key_type }}"
    size: "{{ ctlabs_opendkim_key_length | int }}"
    mode: '0640'
    owner: "{{ ctlabs_opendkim.defaults.service.user }}"
    group: "{{ ctlabs_opendkim.defaults.service.group }}"
  register: ctlabs_opendkim_key_gen
  notify: ctlabs_opendkim.handlers.service.restart

- name: ctlabs_opendkim.tasks.config.key.dns_record
  ansible.builtin.script: >-
    files/dkim_dns_record.py
    {{ ctlabs_opendkim.defaults.key.dir }}/{{ ctlabs_opendkim_domain }}/{{ ctlabs_opendkim_selector }}.private
    {{ ctlabs_opendkim.defaults.key.dir }}/{{ ctlabs_opendkim_domain }}/{{ ctlabs_opendkim_selector }}.txt
    {{ ctlabs_opendkim_selector }}
    {{ ctlabs_opendkim_domain }}
    {{ ctlabs_opendkim_key_algorithm }}
  args:
    creates: "{{ ctlabs_opendkim.defaults.key.dir }}/{{ ctlabs_opendkim_domain }}/{{ ctlabs_opendkim_selector }}.txt"

- name: ctlabs_opendkim.tasks.config.file
  template:
    src : "{{ ctlabs_opendkim.defaults.config.template }}"
    dest: "{{ ctlabs_opendkim.defaults.config.file }}"
  notify: ctlabs_opendkim.handlers.service.restart

- name: ctlabs_opendkim.tasks.config.files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ ctlabs_opendkim.defaults.config.dir }}/{{ item }}"
    owner: root
    group: "{{ ctlabs_opendkim.defaults.service.group }}"
    mode: '0640'
  loop: "{{ ctlabs_opendkim.defaults.config.files }}"
  notify: ctlabs_opendkim.handlers.service.restart

- name: ctlabs_opendkim.tasks.config.postfix_user
  user:
    name: postfix
    groups: "{{ ctlabs_opendkim.defaults.service.group }}"
    append: true
  notify: ctlabs_opendkim.handlers.service.postfix_reload
