---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_opendkim/tasks/main.yml
# Description : main
# ------------------------------------------------------------------------------

- import_tasks: precheck.yml
  tags:
    - ctlabs_opendkim
    - ctlabs_opendkim.precheck
    - ctlabs_opendkim.package
    - ctlabs_opendkim.config
    - ctlabs_opendkim.service

- import_tasks: package.yml
  tags:
    - ctlabs_opendkim
    - ctlabs_opendkim.package

- import_tasks: config.yml
  tags:
    - ctlabs_opendkim
    - ctlabs_opendkim.config

- import_tasks: service.yml
  tags:
    - ctlabs_opendkim
    - ctlabs_opendkim.service
