---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_opendkim/tasks/package.yml
# Description : package
# ------------------------------------------------------------------------------

- name: ctlabs_opendkim.tasks.package.install.redhat
  when: ctg_os_family == 'redhat'
  ansible.builtin.dnf:
    name: "{{ ctlabs_opendkim['settings']['pkgs']['redhat'] | map(attribute='name') | list }}"
    state: present
    enablerepo: epel,crb

- name: ctlabs_opendkim.tasks.package.install.debian
  when: ctg_os_family == 'debian'
  ansible.builtin.apt:
    name: "{{ ctlabs_opendkim['settings']['pkgs']['debian'] | map(attribute='name') | list }}"
    state: present
