---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_opendkim/tasks/service.yml
# Description : service
# ------------------------------------------------------------------------------

- name: ctlabs_opendkim.tasks.service.start
  ansible.builtin.service:
    name: "{{ ctlabs_opendkim['settings']['service']['name'] }}"
    state: started
    enabled: true
