---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_tempo/tasks/facts.yml
# Description : write local facts
# ------------------------------------------------------------------------------

- name: ctlabs_tempo.tasks.facts.write
  when: query('ansible.builtin.fileglob', 'templates/facts.json.j2') | length > 0
  tags:
    - setup
    - ctlabs_tempo.facts
  template:
    src : facts.json.j2
    dest: "{{ ctg_facts_dir }}/ctlabs_tempo.fact"
