---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_tempo/tasks/main.yml
# Description : main tasks file
# ------------------------------------------------------------------------------

- import_tasks: precheck.yml
  tags:
    - ctlabs_tempo
    - ctlabs_tempo.precheck
    - ctlabs_tempo.package
    - ctlabs_tempo.config
    - ctlabs_tempo.service

- import_tasks: package.yml
  tags:
    - ctlabs_tempo
    - ctlabs_tempo.package

- import_tasks: config.yml
  tags:
    - ctlabs_tempo
    - ctlabs_tempo.config

- import_tasks: service.yml
  tags:
    - ctlabs_tempo
    - ctlabs_tempo.service
