---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_k3s/tasks/package.yml
# Description : packages
# ------------------------------------------------------------------------------

- name: ctlabs_k3s.tasks.package.debian
  when: ctg_os_family == 'debian'
  block:
    - name: ctlabs_k3s.tasks.package.debian.update.cache
      apt:
        update_cache: true

    - name: ctlabs_k3s.tasks.package.install.name
      when: item.name is defined
      apt:
        name  : "{{ item.name }}"
      loop    : "{{ ctlabs_k3s.defaults.pkgs[ctg_os_family] }}"
      register: result
      until   : result is success

    - name: ctlabs_k3s.tasks.package.install.url
      when: item.url is defined
      apt:
        deb   : "{{ item.url }}"
      loop    : "{{ ctlabs_k3s.defaults.pkgs[ctg_os_family] }}"
      register: result
      until   : result is success

- name: ctlabs_k3s.tasks.package.k3s.install
  get_url:
    url  : "{{ ctlabs_k3s.defaults.pkgs.k3s.uri }}"
    dest : "{{ ctlabs_k3s.defaults.pkgs.k3s.path }}"
    mode : "{{ ctlabs_k3s.defaults.pkgs.k3s.mode }}"
  register: result
  until   : result is success
