---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_k3s/tasks/service.yml
# Description : service
# ------------------------------------------------------------------------------

- name: ctlabs_k3s.tasks.service.server
  when: ctlabs_k3s_role == "server"
  block:
    - name: ctlabs_k3s.tasks.service.server.present
      template:
        src  : "{{ ctlabs_k3s.defaults.service.server.template }}"
        dest : "{{ ctg_systemd_dir + '/' + ctlabs_k3s.defaults.service.server.name }}"
      notify: ctlabs_k3s.handlers.server.systemd.reload

    - name: ctlabs_k3s.tasks.service.server.started
      service:
        name  : "{{ ctlabs_k3s.defaults.service.server.name }}"
        state : started

- name: ctlabs_k3s.tasks.service.control
  when: ctlabs_k3s_role == "control"
  block:
    - name: ctlabs_k3s.tasks.service.control.sysconfig.present
      template:
        src  : "{{ ctlabs_k3s.defaults.sysconfig.control.template }}"
        dest : "{{ ctlabs_k3s.defaults.sysconfig.control.name     }}"

    - name: ctlabs_k3s.tasks.service.control.present
      template:
        src  : "{{ ctlabs_k3s.defaults.service.control.template }}"
        dest : "{{ ctg_systemd_dir + '/' + ctlabs_k3s.defaults.service.control.name }}"
      notify: ctlabs_k3s.handlers.control.systemd.reload

    - name: ctlabs_k3s.tasks.service.control.started
      service:
        name  : "{{ ctlabs_k3s.defaults.service.control.name }}"
        state : started

- name: ctlabs_k3s.tasks.service.worker
  when: ctlabs_k3s_role == "worker"
  block:
    - name: ctlabs_k3s.tasks.service.worker.sysconfig.present
      template:
        src  : "{{ ctlabs_k3s.defaults.sysconfig.worker.template }}"
        dest : "{{ ctlabs_k3s.defaults.sysconfig.worker.name     }}"

    - name: ctlabs_k3s.tasks.service.worker.present
      template:
        src  : "{{ ctlabs_k3s.defaults.service.worker.template }}"
        dest : "{{ ctg_systemd_dir + '/' + ctlabs_k3s.defaults.service.worker.name }}"
      notify: ctlabs_k3s.handlers.worker.systemd.reload

    - name: ctlabs_k3s.tasks.service.worker.started
      service:
        name  : "{{ ctlabs_k3s.defaults.service.worker.name }}"
        state : started
    
- name: ctlabs_k3s.tasks.service.cluster
  when: ctlabs_k3s_role == "server"
  block:
    - name: ctlabs_k3s.tasks.service.cluster.ready
      vars:
        ansible_python_interpreter: /usr/sbin/ip vrf exec default /usr/bin/python3
      ansible.builtin.wait_for:
        host: "{{ ansible_nodename }}"
        port: 6443
        delay: 10

    - name: ctlabs_k3s.tasks.service.cluster.api_ready
      vars:
        ansible_python_interpreter: /usr/sbin/ip vrf exec default /usr/bin/python3
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      shell: /usr/bin/k3s kubectl cluster-info
      register: cluster_info
      until: cluster_info.rc == 0
      retries: 10
      delay: 10 

    # ------------------------------------------------------------------------------
    # GATEWAY-API / TRAEFIK GATEWAYCLASS / ARGOCD HTTPROUTE
    # ------------------------------------------------------------------------------
    - name: ctlabs_k3s.tasks.service.gateway_api
      when: ctlabs_k3s_gateway_api_enabled
      block:
        - name: ctlabs_k3s.tasks.service.gateway_api.crds.available
          when: ctlabs_k3s_gateway_api_provider == "traefik"
          environment:
            KUBECONFIG: /etc/rancher/k3s/k3s.yaml
          shell: /usr/bin/k3s kubectl get crd gateways.gateway.networking.k8s.io
          register: res_gw_crds
          until   : res_gw_crds is success
          retries : 30
          delay   : 5

        - name: ctlabs_k3s.tasks.service.gateway_api.traefik
          when: ctlabs_k3s_gateway_api_provider == "traefik"
          block:
            - name: ctlabs_k3s.tasks.service.gateway_api.traefik.manifests_dir
              ansible.builtin.file:
                path : /var/lib/rancher/k3s/server/manifests
                state: directory
                mode : '0755'

            - name: ctlabs_k3s.tasks.service.gateway_api.traefik.manifest
              template:
                src: k3s-traefik-config.yml.j2
                dest: /var/lib/rancher/k3s/server/manifests/k3s-traefik-config.yaml

        - name: ctlabs_k3s.tasks.service.gateway.gateway
          when: ctlabs_k3s_gateway_api_provider == "traefik"
          environment:
            KUBECONFIG: /etc/rancher/k3s/k3s.yaml
          kubernetes.core.k8s:
            state: present
            definition:
              apiVersion: gateway.networking.k8s.io/v1
              kind: Gateway
              metadata:
                name: traefik-gateway
                namespace: kube-system
              spec:
                gatewayClassName: traefik
                listeners:
                  - name: web
                    port: 8000
                    protocol: HTTP
                    allowedRoutes:
                      namespaces:
                        from: All
                  - name: websecure
                    port: 8443
                    protocol: HTTPS
                    tls:
                      mode: Terminate
                      certificateRefs:
                        - name: argocd-tls
                          namespace: argo
                    allowedRoutes:
                      namespaces:
                        from: All
          register: res_gateway
          until   : res_gateway is success
          retries : 30
          delay   : 5

    - name: ctlabs_k3s.tasks.service.gateway_envoy
      when:
        - ctlabs_k3s_gateway_api_enabled
        - ctlabs_k3s_gateway_api_provider == "envoy-gateway"
      block:
        - name: ctlabs_k3s.tasks.service.gateway_envoy.install
          get_url:
            url  : https://github.com/envoyproxy/gateway/releases/download/v1.0.1/install.yaml
            dest : /tmp/gateway-ctrl-deployment.yml
          register: res_gateway_ctrl
          until   : res_gateway_ctrl is success

        - name: ctlabs_k3s.tasks.service.gateway_envoy.deploy
          environment:
            KUBECONFIG: /etc/rancher/k3s/k3s.yaml
          kubernetes.core.k8s:
            src: /tmp/gateway-ctrl-deployment.yml


    - name: ctlabs_k3s.tasks.service.ingress
      when:
        - ctlabs_k3s_ingress_enabled
        - ctlabs_k3s_ingress_type == "nginx"
      block:
        - name: ctlabs_k3s.tasks.service.ingress.download
          get_url:
            url : "{{ ctlabs_k3s.defaults.ingress.nginx.url }}"
            dest: /tmp/ingress-deployment.yml

        - name: ctlabs_k3s.tasks.service.ingress.lb.present
          template:
            src: "{{ ctlabs_k3s.defaults.ingress.nginx.lb.template }}"
            dest: "{{ ctlabs_k3s.defaults.ingress.nginx.lb.file }}"

        - name: ctlabs_k3s.tasks.service.ingress.deploy
          environment:
            KUBECONFIG: /etc/rancher/k3s/k3s.yaml
          kubernetes.core.k8s:
            state: present
            src: /tmp/ingress-deployment.yml

        - name: ctlabs_k3s.tasks.service.ingress.lb.deploy
          environment:
            KUBECONFIG: /etc/rancher/k3s/k3s.yaml
          kubernetes.core.k8s:
            state: present
            src: "{{ ctlabs_k3s.defaults.ingress.nginx.lb.file }}"
