---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_rke2/tasks/service.yml
# Description : service
# ------------------------------------------------------------------------------

- name: ctlabs_rke2.tasks.service.server
  when: ctlabs_rke2_role == "server"
  block:
    - name: ctlabs_rke2.tasks.service.server.present
      template:
        src  : "{{ ctlabs_rke2.defaults.service.server.template }}"
        dest : "{{ ctg_systemd_dir + '/' + ctlabs_rke2.defaults.service.server.name }}"
      notify: ctlabs_rke2.handlers.server.systemd.reload
    
    - name: ctlabs_rke2.tasks.service.server.started
      service:
        name  : "{{ ctlabs_rke2.defaults.service.server.name }}"
        state : started
    
- name: ctlabs_rke2.tasks.service.control
  when: ctlabs_rke2_role == "control"
  block:
    - name: ctlabs_rke2.tasks.service.control.sysconfig.present
      template:
        src  : "{{ ctlabs_rke2.defaults.sysconfig.control.template }}"
        dest : "{{ ctlabs_rke2.defaults.sysconfig.control.name     }}"

    - name: ctlabs_rke2.tasks.service.control.present
      template:
        src  : "{{ ctlabs_rke2.defaults.service.control.template }}"
        dest : "{{ ctg_systemd_dir + '/' + ctlabs_rke2.defaults.service.control.name }}"
      notify: ctlabs_rke2.handlers.control.systemd.reload

    - name: ctlabs_rke2.tasks.service.control.started
      service:
        name  : "{{ ctlabs_rke2.defaults.service.control.name }}"
        state : started

- name: ctlabs_rke2.tasks.service.worker
  when: ctlabs_rke2_role == "worker"
  block:
    - name: ctlabs_rke2.tasks.service.worker.sysconfig.present
      template:
        src  : "{{ ctlabs_rke2.defaults.sysconfig.worker.template }}"
        dest : "{{ ctlabs_rke2.defaults.sysconfig.worker.name     }}"

    - name: ctlabs_rke2.tasks.service.worker.present
      template:
        src  : "{{ ctlabs_rke2.defaults.service.worker.template }}"
        dest : "{{ ctg_systemd_dir + '/' + ctlabs_rke2.defaults.service.worker.name }}"
      notify: ctlabs_rke2.handlers.worker.systemd.reload

    - name: ctlabs_rke2.tasks.service.worker.started
      service:
        name  : "{{ ctlabs_rke2.defaults.service.worker.name }}"
        state : started
    
- name: ctlabs_rke2.tasks.service.cluster
  when: ctlabs_rke2_role == "server"
  block:
    - name: ctlabs_rke2.tasks.service.cluster.ready
      vars:
        ansible_python_interpreter: /usr/sbin/ip vrf exec default /usr/bin/python3
      ansible.builtin.wait_for:
        host  : "{{ ansible_nodename }}"
        port  : 6443
        delay : 10 

    - name: ctlabs_rke2.tasks.service.cluster.ingress.ready
      when: ctlabs_rke2_ingress_type == "ingress"
      vars:
        ansible_python_interpreter: /usr/sbin/ip vrf exec default /usr/bin/python3
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml
      kubernetes.core.k8s_info:
        kind      : Daemonset
        name      : rke2-ingress-nginx-controller
        namespace : kube-system
        wait      : true

    # ------------------------------------------------------------------------------
    # GATEWAY-API / TRAEFIK GATEWAYCLASS / ARGOCD HTTPROUTE
    # ------------------------------------------------------------------------------
    - name: ctlabs_rke2.tasks.service.gateway_api
      when: ctlabs_rke2_ingress_type == "gateway_api"
      block:
        - name: ctlabs_rke2.tasks.service.gateway_api.crds.download
          get_url:
            url  : "{{ ctlabs_rke2.defaults.ingress.gateway_api.crds }}"
            dest : "{{ ctlabs_rke2.defaults.ingress.gateway_api.file }}"
          register: res_crds_dl
          until   : res_crds_dl is success

        - name: ctlabs_rke2.tasks.service.gateway_api.crds.apply
          environment:
            KUBECONFIG: /etc/rancher/rke2/rke2.yaml
          shell: >
            {{ ctlabs_rke2.defaults.pkgs.kubectl.path }} apply
            --server-side -f {{ ctlabs_rke2.defaults.ingress.gateway_api.file }}
          register: gw_crds
          until  : gw_crds is success
          retries: 3
          delay  : 5

        - name: ctlabs_rke2.tasks.service.gateway_api.envoy
          when: ctlabs_rke2_ingress_provider == "envoy-gateway"
          block:
            - name: ctlabs_rke2.tasks.service.gateway_api.envoy.install
              get_url:
                url  : "https://github.com/envoyproxy/gateway/releases/download/v{{ versions.envoy }}/install.yaml"
                dest : /tmp/gateway-ctrl-deployment.yml
              register: res_envoy_dl
              until   : res_envoy_dl is success

            - name: ctlabs_rke2.tasks.service.gateway_api.envoy.deploy
              environment:
                KUBECONFIG: /etc/rancher/rke2/rke2.yaml
              kubernetes.core.k8s:
                src: /tmp/gateway-ctrl-deployment.yml

        - name: ctlabs_rke2.tasks.service.argocd.gateway_objects
          environment:
            KUBECONFIG: /etc/rancher/rke2/rke2.yaml
          block:
            - name: ctlabs_rke2.tasks.service.argocd.namespaces
              kubernetes.core.k8s:
                state: present
                definition:
                  apiVersion: v1
                  kind: Namespace
                  metadata:
                    name: "{{ item }}"
              loop:
                - argo
                - "{{ ctlabs_rke2.defaults.ingress.traefik.ns }}"

            - name: ctlabs_rke2.tasks.service.argocd.tls_secret
              kubernetes.core.k8s:
                state: present
                definition:
                  apiVersion: v1
                  kind: Secret
                  metadata:
                    name: argocd-tls
                    namespace: argo
                  type: kubernetes.io/tls
                  data:
                    tls.crt: "{{ lookup('file', '/etc/ca-ctlabs/' + ansible_nodename + '.crt') | b64encode }}"
                    tls.key: "{{ lookup('file', '/etc/ca-ctlabs/' + ansible_nodename + '.prv') | b64encode }}"

            - name: ctlabs_rke2.tasks.service.argocd.reference_grant
              kubernetes.core.k8s:
                state: present
                definition:
                  apiVersion: gateway.networking.k8s.io/v1
                  kind: ReferenceGrant
                  metadata:
                    name: argocd-grant
                    namespace: argo
                  spec:
                    from:
                      - group: gateway.networking.k8s.io
                        kind: Gateway
                        namespace: "{{ ctlabs_rke2.defaults.ingress.traefik.ns }}"
                    to:
                      - group: ""
                        kind: Secret

            - name: ctlabs_rke2.tasks.service.gateway.attachment_grant
              kubernetes.core.k8s:
                state: present
                definition:
                  apiVersion: gateway.networking.k8s.io/v1
                  kind: ReferenceGrant
                  metadata:
                    name: allow-argo-routes
                    namespace: "{{ ctlabs_rke2.defaults.ingress.traefik.ns }}"
                  spec:
                    from:
                      - group: gateway.networking.k8s.io
                        kind: HTTPRoute
                        namespace: argo
                    to:
                      - group: gateway.networking.k8s.io
                        kind: Gateway

            - name: ctlabs_rke2.tasks.service.argocd.gateway
              when: ctlabs_rke2_ingress_provider == "traefik"
              kubernetes.core.k8s:
                state: present
                definition:
                  apiVersion: gateway.networking.k8s.io/v1
                  kind: Gateway
                  metadata:
                    name: traefik-gateway
                    namespace: "{{ ctlabs_rke2.defaults.ingress.traefik.ns }}"
                  spec:
                    gatewayClassName: traefik
                    listeners:
                      - name: web
                        port: 8000
                        protocol: HTTP
                        allowedRoutes:
                          namespaces:
                            from: All
                      - name: websecure
                        port: 8443
                        protocol: HTTPS
                        tls:
                          mode: Terminate
                          certificateRefs:
                            - name: argocd-tls
                              namespace: argo
                        allowedRoutes:
                          namespaces:
                            from: All

            - name: ctlabs_rke2.tasks.service.argocd.httproute
              kubernetes.core.k8s:
                state: present
                definition:
                  apiVersion: gateway.networking.k8s.io/v1
                  kind: HTTPRoute
                  metadata:
                    name: argocd-server
                    namespace: argo
                  spec:
                    parentRefs:
                      - name: traefik-gateway
                        namespace: "{{ ctlabs_rke2.defaults.ingress.traefik.ns }}"
                        sectionName: web
                      - name: traefik-gateway
                        namespace: "{{ ctlabs_rke2.defaults.ingress.traefik.ns }}"
                        sectionName: websecure
                    rules:
                      - matches:
                          - path:
                              type: PathPrefix
                              value: /
                        backendRefs:
                          - name: argocd-server
                            port: 80
