---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_sssd/tasks/facts.yml
# Description : write local facts
# ------------------------------------------------------------------------------

- name: ctlabs_sssd.tasks.facts.write
  tags:
    - setup
    - ctlabs_sssd.facts
  template:
    src : facts.json.j2
    dest: "{{ ctg_facts_dir }}/ctlabs_sssd.fact"
