---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_sssd/tasks/precheck.yml
# Description : prechecks
# ------------------------------------------------------------------------------

- name: ctlabs_sssd.tasks.precheck
  block:
    - name: ctlabs_sssd.tasks.precheck.os.supported
      assert:
        that     : ctg_os is in ctlabs_sssd.os
        fail_msg : "OS[{{ ctg_os }}] is not supported!"
    - name: ctlabs_sssd.tasks.precheck.addc
      assert:
        that     : ansible_nodename is not in ctlabs_sssd.defaults.config.dc.hosts
        fail_msg : "Host {{ ansible_nodename }} is DC!"
  rescue:
    - name: ctlabs_sssd.tasks.precheck.skip.unsupported
      meta: end_host

# backend
- name: ctlabs_sssd.tasks.precheck.backend.var
  set_fact:
    ctlabs_sssd_backend: "{{ ctlabs_sssd_backend | default('ldap') | upper }}"

- name: ctlabs_sssd.tasks.precheck.backend.local_fact
  set_fact:
    ctlabs_sssd_backend: "{{ ctg_facts.ctlabs_sssd.backend | default(ctlabs_sssd_backend) }}"

# domain
- name: ctlabs_sssd.tasks.precheck.domain.var
  set_fact:
    ctlabs_sssd_domain: "{{ ctlabs_sssd_domain | default('ad.ctlabs.internal') }}"

- name: ctlabs_sssd.tasks.precheck.domain.local_fact
  set_fact:
    ctlabs_sssd_domain: "{{ ctg_facts.ctlabs_sssd.domain | default(ctlabs_sssd_domain) }}"

# derived
- name: ctlabs_sssd.tasks.precheck.domain_path
  set_fact:
    ctlabs_sssd_domain_path: "dc={{ ctlabs_sssd_domain.split('.') | join(',dc=') }}"

- name: ctlabs_sssd.tasks.precheck.realm
  set_fact:
    ctlabs_sssd_realm: "{{ ctlabs_sssd_domain | upper }}"
