---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_ad/tasks/leave.yml
# Description : leaving the windows domain
# ------------------------------------------------------------------------------

- name: ctlabs_ad.tasks.leave.domain
  block:
    - name: ctlabs_ad.tasks.leave.domain.leave
      microsoft.ad.membership:
        state                  : workgroup
        workgroup_name         : WORKGROUP
        domain_admin_user      : "{{ ctlabs_ad_dc_join_user }}@{{ ctlabs_ad.defaults.config.dc.realm }}"
        domain_admin_password  : "{{ ctlabs_ad_dc_join_pass }}"
        domain_server          : "{{ ctlabs_ad_domain_server }}"
        hostname               : "{{ ctlabs_ad_join_hostname }}"
        reboot                 : true
        reboot_timeout         : 600
      register: ctlabs_ad_leave_result

    - name: ctlabs_ad.tasks.leave.domain.delete_ad_object
      microsoft.ad.computer:
        state           : absent
        identity        : "{{ ctlabs_ad_join_hostname }}"
        domain_username : "{{ hostvars[inventory_hostname]['ctlabs_ad_dc_join_user'] }}@{{ ctlabs_ad.defaults.config.dc.realm }}"
        domain_password : "{{ hostvars[inventory_hostname]['ctlabs_ad_dc_join_pass'] }}"
        domain_server   : "{{ ctlabs_ad_domain_server }}"
      delegate_to: "{{ ctlabs_ad_domain_server }}"
      #vars:
        #ansible_connection                   : winrm
        #ansible_winrm_transport              : ntlm
        #ansible_winrm_server_cert_validation : ignore
        #ansible_user                         : "{{ hostvars[inventory_hostname]['ctlabs_ad_dc_join_user'] }}@{{ ctlabs_ad.defaults.config.dc.realm }}"
        #ansible_password                     : "{{ hostvars[inventory_hostname]['ctlabs_ad_dc_join_pass'] }}"
