---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_ad/tasks/main.yml
# Description : main entry point for the ctlabs_ad role
# ------------------------------------------------------------------------------

- import_tasks: precheck.yml
  tags:
    - ctlabs_ad
    - ctlabs_ad.precheck

- import_tasks: package.yml
  tags:
    - ctlabs_ad
    - ctlabs_ad.package

- import_tasks: config.yml
  tags:
    - ctlabs_ad
    - ctlabs_ad.config

- import_tasks: dc.yml
  when: ctlabs_ad_role in ['master', 'slave']
  tags:
    - ctlabs_ad
    - ctlabs_ad.dc

- import_tasks: join.yml
  when:
    - ctlabs_ad_role == 'member'
    - not ctlabs_ad_leave
  tags:
    - ctlabs_ad
    - ctlabs_ad.join

- import_tasks: service.yml
  when:
    - ctlabs_ad_role == 'member'
    - not ctlabs_ad_leave
  tags:
    - ctlabs_ad
    - ctlabs_ad.service

- import_tasks: leave.yml
  when:
    - ctlabs_ad_role == 'member'
    - ctlabs_ad_leave
  tags:
    - ctlabs_ad
    - ctlabs_ad.leave
