---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_ad/tasks/package.yml
# Description : main ctlabs_ad tasks file.
# ------------------------------------------------------------------------------
