---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_ad/tasks/service.yml
# Description : main ctlabs_ad services
# ------------------------------------------------------------------------------
