---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_vault/tasks/service.yml
# Description : service
# ------------------------------------------------------------------------------

- name: ctlabs_vault.tasks.service.server.start
  when: ctlabs_vault_install_type == 'server'
  service:
    name    : "{{ ctlabs_vault.defaults.service.server.name }}"
    enabled : true
    state   : started

- name: ctlabs_vault.tasks.service.agent.start
  when: ctlabs_vault_install_type == 'agent'
  service:
    name    : "{{ ctlabs_vault.defaults.service.agent.name }}"
    enabled : true
    state   : started

- name: ctlabs_vault.tasks.service.proxy.start
  when: ctlabs_vault_install_type == 'proxy'
  service:
    name    : "{{ ctlabs_vault.defaults.service.proxy.name }}"
    enabled : true
    state   : started
