---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_kind/tasks/package.yml
# Description : packages
# ------------------------------------------------------------------------------

- name: ctlabs_kind.tasks.package.install
  package:
    name  : "{{ item.name }}"
    state : present
  loop    : "{{ ctlabs_kind.defaults.pkgs[ctg_os_family] }}"
  register: result
  until   : result is success

- name: ctlabs_kind.tasks.package.kindinstall
  get_url:
    url  : "{{ ctlabs_kind.defaults.pkgs.kind.url  }}"
    dest : "{{ ctlabs_kind.defaults.pkgs.kind.path }}"
    mode : "{{ ctlabs_kind.defaults.pkgs.kind.mode }}"

- name: ctlabs_kind.tasks.package.kubectl.install
  get_url:
    url  : "{{ ctlabs_kind.defaults.pkgs.kubectl.url  }}"
    dest : "{{ ctlabs_kind.defaults.pkgs.kubectl.path }}"
    mode : "{{ ctlabs_kind.defaults.pkgs.kubectl.mode }}"
