---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_blackbox_exporter/tasks/facts.yml
# Description : write local facts
# ------------------------------------------------------------------------------

- name: ctlabs_blackbox_exporter.tasks.facts.write
  tags:
    - setup
    - ctlabs_blackbox_exporter.facts
  template:
    src : facts.json.j2
    dest: "{{ ctg_facts_dir }}/ctlabs_blackbox_exporter.fact"
