---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_prometheus/tasks/precheck.yml
# Description : prechecks
# ------------------------------------------------------------------------------

- name: ctlabs_prometheus.tasks.precheck
  block:
    - name: ctlabs_prometheus.tasks.precheck.os.supported
      assert:
        that: ctg_os is in ctlabs_prometheus.os
        fail_msg: "OS [{{ ctg_os }}] is not supported!"
  rescue:
    - name: ctlabs_prometheus.tasks.precheck.skip.unsupported
      meta: end_host

- name: ctlabs_prometheus.tasks.precheck.mtls.client
  set_fact:
    ctlabs_prometheus_mtls_client: "{{ ctg_facts.ctlabs_prometheus.mtls.client | default(true) }}"
