---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_graphify/handlers/main.yml
# Description : handlers
# ------------------------------------------------------------------------------

- name: ctlabs_graphify.handlers.apt.update_cache
  apt:
    update_cache: yes
