---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_graphify/handlers/main.yml
# Description : handlers
# ------------------------------------------------------------------------------

- name: ctlabs_graphify.handlers.service.restart
  systemd_service:
    name          : "{{ ctlabs_graphify.defaults.service.name }}"
    state         : restarted
    daemon_reload : true
