---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_graphify/defaults/main.yml
# Description : main defaults file
# ------------------------------------------------------------------------------

versions:
  graphifyy: 0.8.35

ctlabs_graphify:
  defaults:
    pkgs:
      debian:
        - name: python3
        - name: python3-pip
        - name: python3-venv
        - name: python3-yaml
      redhat:
        - name: python3.11
        - name: python3.11-pip
        - name: python3.11-devel
        - name: python3.11-pyyaml
    python:
      debian: python3
      redhat: python3.11
    pip_executable:
      debian: pip3
      redhat: pip3.11
    pipx:
      bin_dir: /usr/local/bin
      home   : /opt/pipx
    config:
      user  : graphify
      group : graphify
      dir   : /etc/graphify
    projects:
      - dir : /root/ctlabs-ansible
        yaml_extract: true
      - dir : /root/ctlabs-terraform
        yaml_extract: false
      - dir : /root/ctlabs-tools
        yaml_extract: false
  os:
    - debian12
    - centos9
    - redhat9
