---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_openclaw/handlers/main.yml
# Description : handlers
# ------------------------------------------------------------------------------

- name: ctlabs_openclaw.handlers.openclaw.service.restarted
  systemd_service:
    name          : "{{ ctlabs_openclaw.defaults.service.name }}"
    state         : restarted
    daemon_reload : true
