---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_kind/defaults/main.yml
# Description : main defaults
# ------------------------------------------------------------------------------

versions:
  kind        : 0.31.0
  k8s         : 1.35.0
  kubectl     : 1.35.0
  helm        : 4.1.4
  nginx       : 1.15.0
  gateway_api : 1.5.0


ctlabs_kind:
  defaults:
    pkgs:
      debian:
        - name: podman
        - name: python3-kubernetes
      redhat:
        - name: podman
        - name: python3-kubernetes
      kind:
        url    : "https://kind.sigs.k8s.io/dl/v{{ versions.kind }}/kind-linux-amd64"
        path   : /usr/bin/kind
        mode   : '0750'
      kubectl:
        url    : "https://dl.k8s.io/release/v{{ versions.kubectl }}/bin/linux/amd64/kubectl"
        path   : /usr/bin/kubectl
        mode   : '0750'
      helm:
        url    : "https://get.helm.sh/helm-v{{ versions.helm }}-linux-amd64.tar.gz"
        tmptar : /tmp/helm.tar.gz
        tmpdir : /tmp
        tardir : /tmp/linux-amd64
        path   : /usr/bin/helm
        mode   : '0750'
    config:
      plane   : "single"           # "single" or "multi"
      name    : "ctlabs"
      image   : "kindest/node:v{{ versions.k8s }}"
      profile :
        template : kind.profile.j2
        file     : /etc/profile.d/kind.sh
      cluster :
        template : kind-cluster.yml.j2
        file     : /tmp/kind-cluster.yml
      node    :
        count   : 1
      ingress:
        enabled: false
        type   : "nginx"     # Options: 'traefik', 'nginx'
      gateway_api:
        enabled : true
        provider: "traefik"  # Options: 'traefik', 'envoy-gateway'
    ingress:
      nginx:
        url: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v{{ versions.nginx }}/deploy/static/provider/kind/deploy.yaml"
        file: /tmp/ingress-nginx-deploy.yaml
      gateway_api:
        crds: "https://github.com/kubernetes-sigs/gateway-api/releases/download/v{{ versions.gateway_api }}/standard-install.yaml"
        file: /tmp/gateway-api-crds.yaml
    repos : []
    charts: []
    service:
      main:
        cluster:
          config : /tmp/kind-cluster.yml
    proxy:
      interface : enp0s2
  os:
    - centos9
    - redhat9
    - debian12
  virtype:
    - kvm
