---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_foreman/tasks/facts.yml
# Description : write local facts
# ------------------------------------------------------------------------------

- name: ctlabs_foreman.tasks.facts.write
  tags:
    - setup
    - ctlabs_foreman.facts
  template:
    src : facts.json.j2
    dest: "{{ ctg_facts_dir }}/ctlabs_foreman.fact"
