---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_graphify/tasks/main.yml
# Description : main tasks file
# ------------------------------------------------------------------------------

- import_tasks: precheck.yml
  tags:
    - ctlabs_graphify
    - ctlabs_graphify.precheck
    - ctlabs_graphify.package
    - ctlabs_graphify.config
    - ctlabs_graphify.service

- import_tasks: package.yml
  tags:
    - ctlabs_graphify
    - ctlabs_graphify.package

- import_tasks: config.yml
  tags:
    - ctlabs_graphify
    - ctlabs_graphify.config

- import_tasks: service.yml
  tags:
    - ctlabs_graphify
    - ctlabs_graphify.service
