---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_auditd/handlers/main.yml
# Description : handlers
# ------------------------------------------------------------------------------

# Use this handler if you update /etc/audit/auditd.conf
- name: ctlabs_auditd.handlers.service.restart
  ansible.builtin.command: service {{ ctlabs_auditd.defaults.service.name }} restart

# Use this handler if you update /etc/audit/rules.d/ files
- name: ctlabs_auditd.handlers.rules.reload
  ansible.builtin.command: /sbin/augenrules --load
