---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_postfix/meta/main.yml
# Description : role dependencies
# ------------------------------------------------------------------------------

dependencies:
  - ctlabs_alloy
