---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_opendkim/meta/main.yml
# Description : role dependencies
# ------------------------------------------------------------------------------

dependencies:
  - ctlabs_postfix
