---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_helm/defaults/main.yml
# Description : main defaults
# ------------------------------------------------------------------------------

versions:
  helm: 4.1.4

ctlabs_helm:
  defaults:
    bin:
      url    : "https://get.helm.sh/helm-v{{ versions.helm }}-linux-amd64.tar.gz"
      tmptar : /tmp/helm.tar.gz
      tmpdir : /tmp
      tardir : /tmp/linux-amd64
      path   : /usr/bin/helm
      mode   : '0750'
    repos : []
    charts: []
    gateway:
      refgrant_api  : "v1"            # Options: 'v1', 'v1beta1' (v1beta1 for k3s bundled Gateway API v1.0.0 CRDs)
      tls_secret    : "argocd-tls"
      grant_name    : "argocd-grant"
      attach_grant  : "allow-argo-routes"
      route_name    : "argocd-server"
      route_backend : "argocd-server"
      route_port    : 80
  os:
    - centos8
    - centos9
    - redhat8
    - redhat9
    - debian11
    - debian12
