---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_ghidra/tasks/facts.yml
# Description : write local facts
# ------------------------------------------------------------------------------

- name: ctlabs_ghidra.tasks.facts.write
  when: query('ansible.builtin.fileglob', 'templates/facts.json.j2') | length > 0
  tags:
    - setup
    - ctlabs_ghidra.facts
  template:
    src : facts.json.j2
    dest: "{{ ctg_facts_dir }}/ctlabs_ghidra.fact"
