---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_gemini_cli/defaults/main.yml
# Description : main defaults
# ------------------------------------------------------------------------------

versions:
  nodejs: node_22.x

ctlabs_gemini_cli:
  defaults:
    repos:
      debian:
        - name: nodesource
          url : "https://deb.nodesource.com/{{ versions.nodejs }}"
          key : https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    pkgs:
      debian: 
        - name: curl
        - name: nodejs
        - name: git
        - name: build-essential
        - name: python3-dev
        - name: libsecret-1-dev
      redhat: []
      npm:
        - name: "@google/gemini-cli"
    config:
      prefdir: /etc/apt/preferences.d
      keydir : /etc/apt/keyrings
      dir     : /home/gemini
      user    : gemini
      group   : gemini
      groups  : [certs]
      profile:
        template: profile_gemini.sh.j2
        file    : /etc/profile.d/gemini.sh
      settings:
        dir     : ~/.gemini
        template: gemini_settings.json.j2
        file    : ~/.gemini/settings.json
    certs:
      dir: /etc/ca-ctlabs
      crt: "{{ ansible_nodename }}.crt"
      key: "{{ ansible_nodename }}.prv"
      ca:  ca-ctlabs.crt
    service:
  os:
    - debian12
    - kali2025
    - kali2026
    - parrot6
    - parrot7
