---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_wazuh/tasks/facts.yml
# Description : write local facts
# ------------------------------------------------------------------------------

- name: ctlabs_wazuh.tasks.facts.write
  tags:
    - setup
    - ctlabs_wazuh.facts
  template:
    src : facts.json.j2
    dest: "{{ ctg_facts_dir }}/ctlabs_wazuh.fact"
