---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_wazuh/tasks/package.yml
# Description : install packages
# ------------------------------------------------------------------------------

- name: ctlabs_wazuh.tasks.package.redhat
  when: ctg_os_family == "redhat"
  block:
    - name: ctlabs_wazuh.tasks.package.redhat.repo.file
      yum_repository:
        name        : "{{ item.name }}"
        description : "{{ item.name }}"
        baseurl     : "{{ item.url  }}"
        gpgkey      : "{{ item.key  }}"
        gpgcheck    : true
        sslverify   : true
      loop: "{{ ctlabs_wazuh.defaults.repos[ctg_os_family] }}"

- name: ctlabs_wazuh.tasks.package.debian
  when: ctg_os_family == "debian"
  block:
    - name: ctlabs_wazuh.tasks.package.debian.repo.key
      get_url:
        url : "{{ item.key }}"
        dest: "/etc/apt/trusted.gpg.d/{{ item.name }}.asc"
      loop: "{{ ctlabs_wazuh.defaults.repos[ctg_os_family] }}"

    - name: ctlabs_wazuh.tasks.package.debian.repo.file
      apt_repository:
        repo : "deb [signed-by=/etc/apt/trusted.gpg.d/{{ item.name }}.asc] {{ item.url }} stable {{ item.type }}"
      loop: "{{ ctlabs_wazuh.defaults.repos[ctg_os_family] }}"

- name: ctlabs_wazuh.tasks.package.install
  package:
    name  : "{{ item.name }}"
    state : present
  loop    : "{{ ctlabs_wazuh.defaults.pkgs[ctg_os_family][ctlabs_wazuh_role] }}"
  register: result
  until   : result is success

- name: ctlabs_wazuh.tasks.package.user.primary_group
  user:
    name  : "{{ ctlabs_wazuh.defaults.service.user }}"
    group : "{{ ctlabs_wazuh.defaults.service.group }}"

- name: ctlabs_wazuh.tasks.package.group.certs.member
  user:
    name  : "{{ item }}"
    groups: "{{ ctlabs_wazuh.defaults.service.groups }}"
    append: true
  loop:
    - wazuh-indexer
    - wazuh-dashboard
  when: ctlabs_wazuh_role == "server"
