---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_opendkim/defaults/main.yml
# Description : defaults
# ------------------------------------------------------------------------------

ctlabs_opendkim:
  defaults:
    pkgs:
      redhat:
        - name: opendkim
        - name: opendkim-tools
      debian:
        - name: opendkim
        - name: opendkim-tools
    config:
      dir : /etc/opendkim
      template: opendkim.conf.j2
      file    : /etc/opendkim.conf
      mode: sv
      socket: unix:/run/opendkim/opendkim.sock
      key_table    : /etc/opendkim/KeyTable
      signing_table: refile:/etc/opendkim/SigningTable
      trusted_hosts: refile:/etc/opendkim/TrustedHosts
      files:
        - KeyTable
        - SigningTable
        - TrustedHosts
    key:
      dir   : /etc/opendkim/keys
      type  : ed25519
      length: 2048
    service:
      name : opendkim
      user : opendkim
      group: opendkim
  os:
    - redhat9
    - centos9
    - debian11
    - debian12
