---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_mailpiler/tasks/service.yml
# Description : enable and start piler services
# ------------------------------------------------------------------------------

- name: ctlabs_mailpiler.tasks.service.systemd.copy
  copy:
    src  : "/usr/libexec/piler/{{ item }}.service"
    dest : "/etc/systemd/system/{{ item }}.service"
    remote_src: true
  loop:
    - piler
    - piler-smtp
    - pilersearch
  when: ctg_os_family == 'redhat'

- name: ctlabs_mailpiler.tasks.service.systemd.reload
  systemd:
    daemon_reload: true
  when: ctg_os_family == 'redhat'

- name: ctlabs_mailpiler.tasks.service.piler.running
  service:
    name    : "{{ ctlabs_mailpiler.defaults.service.piler.name }}"
    enabled : true
    state   : started

- name: ctlabs_mailpiler.tasks.service.pilersearch.running
  service:
    name    : "{{ ctlabs_mailpiler.defaults.service.pilersearch.name }}"
    enabled : true
    state   : started

- name: ctlabs_mailpiler.tasks.service.piler.smtp.running
  service:
    name    : piler-smtp
    enabled : true
    state   : started
