---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_zap/tasks/main.yml
# Description : main task file
# ------------------------------------------------------------------------------

- import_tasks: precheck.yml
  tags:
    - ctlabs_zap
    - ctlabs_zap.precheck
    - ctlabs_zap.package
    - ctlabs_zap.config

- import_tasks: package.yml
  tags:
    - ctlabs_zap
    - ctlabs_zap.package

- import_tasks: config.yml
  tags:
    - ctlabs_zap
    - ctlabs_zap.config

- import_tasks: service.yml
  tags:
    - ctlabs_zap
    - ctlabs_zap.service
