---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_zap/tasks/service.yml
# Description : service
# ------------------------------------------------------------------------------

- name: ctlabs_zap.tasks.service.unit
  template:
    src: zap.service.j2
    dest: "{{ ctg_systemd_dir + '/' + ctlabs_zap.defaults.service.name }}"
  notify: ctlabs_zap.handlers.service.restart

- name: ctlabs_zap.tasks.service.started
  systemd:
    name: "{{ ctlabs_zap.defaults.service.name }}"
    enabled: true
    state: started
