---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_manticore/tasks/precheck.yml
# Description : prechecks
# ------------------------------------------------------------------------------

- name: ctlabs_manticore.tasks.precheck
  block:
    - name: ctlabs_manticore.tasks.precheck.os.supported
      assert:
        that: ctg_os in ctlabs_manticore.os
        fail_msg: "OS [{{ ctg_os }}] is not supported!"
  rescue:
    - name: ctlabs_manticore.tasks.precheck.skip.unsupported
      meta: end_host
