---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_guacamole/defaults/main.yml
# Description : main defaults file
# ------------------------------------------------------------------------------

versions:
  guacamole: 1.6.0

ctlabs_guacamole:
  defaults:
    pkgs:
      redhat:
        - name : guacd
        - name : libguac-client-rdp
        - name : libguac-client-ssh
        - name : libguac-client-vnc
        - name : java
        - name : tomcat
    webapp:
      file : /var/lib/tomcat/webapps/guacamole.war
      #url  : "https://apache.org/dyn/closer.lua/guacamole/{{ versions.guacamole }}/binary/guacamole-{{ versions.guacamole }}.war?action=download"
      url  : "https://dlcdn.apache.org/guacamole/{{ versions.guacamole }}/binary/guacamole-{{ versions.guacamole }}.war?action=download"
    config:
      dir      : /etc/guacamole/
      server:
        template : guacd.conf.j2
        file     : guacd.conf
      client:
        template : guacamole.properties.j2
        file     : guacamole.properties
      user_mapping:
        template : user-mapping.xml.j2
        file     : user-mapping.xml
        users:
          - username: ctlabs
            password: secret123!
            connections:
              - name: "{{ ansible_nodename }}"
                protocol: ssh
                params:
                  hostname     : "{{ ansible_nodename }}"
                  port         : 22
                  username     : root
                  font-size    : 12
                  color-scheme: |
                    foreground: rgb:ff/ff/ff;
                    background: rgb:2e/07/24;
              - name: dc1-vnc
                protocol: vnc
                params:
                  hostname    : 192.168.30.13
                  port        : 5900
                  ignore-cert : true
                  color-depth : 24
                  width       : 1920
                  height      : 1200
              - name: dc01
                protocol: rdp
                params:
                  hostname    : 192.168.30.14
                  port        : 3389
                  ignore-cert : true
                  color-depth : 24
                  width       : 1920
                  height      : 1200
              - name: dc2-vnc
                protocol: vnc
                params:
                  hostname    : 192.168.30.23
                  port        : 5900
                  ignore-cert : true
                  color-depth : 24
                  width       : 1920
                  height      : 1200
              - name: dc02
                protocol: rdp
                params:
                  hostname    : 192.168.30.24
                  port        : 3389
                  ignore-cert : true
                  color-depth : 24
                  width       : 1920
                  height      : 1200
              - name: h3
                protocol: rdp
                params:
                  hostname      : 192.168.10.17
                  port          : 3389
                  ignore-cert   : true
                  color-depth   : 24
                  resize-method : display-update
      httpd:
        template: guacamole.conf.j2
        file:
          debian: /etc/apache2.conf.d/guacamole.conf
          redhat: /etc/httpd/conf.d/guacamole.conf
    handlers:
      httpd:
        debian: apache2.service
        redhat: httpd.service
    service:
      server:
        name : guacd.service
      client:
        name : tomcat.service
  os:
    - centos9
