---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_gemini_cli/tasks/config.yml
# Description : configurations
# ------------------------------------------------------------------------------

- name: ctlabs_gemini_cli.tasks.config.group
  group:
    name   : "{{ ctlabs_gemini_cli.defaults.config.group }}"
    system : true

- name: ctlabs_gemini_cli.tasks.config.user
  user:
    name   : "{{ ctlabs_gemini_cli.defaults.config.user  }}"
    group  : "{{ ctlabs_gemini_cli.defaults.config.group }}"
    system : true

- name: ctlabs_gemini_cli.tasks.config.group.certs.member
  user:
    name  : "{{ ctlabs_gemini_cli.defaults.config.user   }}"
    group : "{{ ctlabs_gemini_cli.defaults.config.group  }}"
    groups: "{{ ctlabs_gemini_cli.defaults.config.groups }}"
    shell : /bin/bash

- name: ctlabs_gemini_cli.tasks.config.gemini.dir
  file:
    path : "{{ ctlabs_gemini_cli.defaults.config.dir }}"
    state: directory
    owner: "{{ ctlabs_gemini_cli.defaults.config.user  }}"
    group: "{{ ctlabs_gemini_cli.defaults.config.group }}"
    mode : '0750'
