---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_gemini_cli/tasks/package.yml
# Description : packages
# ------------------------------------------------------------------------------

- name: ctlabs_gemini_cli.tasks.package.debian
  when: ctg_os_family == 'debian'
  block:
    - name: ctlabs_gemini_cli.tasks.package.debian.keydir
      file:
        path : "{{ ctlabs_gemini_cli.defaults.config.keydir }}"
        state: directory
        mode : '0755'
    
    - name: ctlabs_gemini_cli.tasks.package.debian.repos.key
      get_url:
        url : "{{ item.key }}"
        dest: "{{ ctlabs_gemini_cli.defaults.config.keydir }}/{{ item.name }}.asc"
        mode: '0644'
      loop: "{{ ctlabs_gemini_cli.defaults.repos[ctg_os_family] }}"
    
    - name: ctlabs_gemini_cli.tasks.package.debian.repos.file
      apt_repository:
        repo: "deb [signed-by={{ ctlabs_gemini_cli.defaults.config.keydir }}/{{ item.name }}.asc] {{ item.url }} nodistro main"
        update_cache: yes
      loop: "{{ ctlabs_gemini_cli.defaults.repos[ctg_os_family] }}"

    - name: ctlabs_gemini_cli.tasks.package.debian.nodejs.pin
      template:
        src : nodejs.pref.j2
        dest: "{{ ctlabs_gemini_cli.defaults.config.prefdir }}/{{ item.name }}.pref"
        mode: '0644'
        owner: root
        group: root
      loop: "{{ ctlabs_gemini_cli.defaults.repos[ctg_os_family] }}"
      notify: ctlabs_gemini_cli.handlers.apt.update_cache

    - name: ctlabs_gemini_cli.tasks.package.debian.update.cache
      apt:
        update_cache: true
    
- name: ctlabs_gemini_cli.tasks.package.pkgs.installed
  when: item.when is not defined or item.when
  package:
    name  : "{{ item.name }}"
    state : present
  loop    : "{{ ctlabs_gemini_cli.defaults.pkgs[ctg_os_family] }}"
  register: result
  until   : result is success
    
- name: ctlabs_gemini_cli.tasks.package.gemini-cli.installed
  npm: 
    name  : "{{ item.name }}"
    state : latest
    global: true
  loop: "{{ ctlabs_gemini_cli.defaults.pkgs.npm }}"
