---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_tika/tasks/package.yml
# Description : packages
# ------------------------------------------------------------------------------

- name: ctlabs_tika.tasks.package.java
  package:
    name    : "{{ item.name }}"
    state : present
  loop    : "{{ ctlabs_tika.defaults.pkgs[ctg_os_family] }}"
  register: result
  until   : result is success

- name: ctlabs_tika.tasks.package.directory
  file:
    path  : "{{ ctlabs_tika.defaults.config.dir }}"
    state : directory
    mode  : '0755'

- name: ctlabs_tika.tasks.package.download
  get_url:
    url  : "{{ ctlabs_tika.defaults.download.url }}"
    dest : "{{ ctlabs_tika.defaults.download.jar }}"
    mode : '0644'

- name: ctlabs_tika.tasks.package.user
  user:
    name        : "{{ ctlabs_tika.defaults.service.user }}"
    system      : true
    home        : "{{ ctlabs_tika.defaults.config.dir }}"
    shell       : /usr/sbin/nologin
    create_home : false
