---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_meilisearch/handlers/main.yml
# Description : description
# ------------------------------------------------------------------------------

- name: ctlabs_meilisearch.handlers.service.restart
  service:
    name    : "{{ ctlabs_meilisearch.defaults.service.name }}"
    enabled : true
    state   : restarted

- name: ctlabs_meilisearch.handlers.service.reload
  service:
    name  : "{{ ctlabs_meilisearch.defaults.service.name }}"
    state : reloaded
