---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_k8s/tasks/service.yml
# Description : service
# ------------------------------------------------------------------------------

#- name: ctlabs_k8s.tasks.service.present
#  template:
#    src  : "{{ ctlabs_k8s.defaults.service.template }}"
#    dest : "{{ ctg_systemd_dir + '/' + ctlabs_k8s.defaults.service.name }}"
#  notify: ctlabs_k8s.handlers.systemd.reload

#- name: ctlabs_k8s.tasks.service.kubelet.started
#  service:
#    name  : "{{ ctlabs_k8s.defaults.service.name }}"
#    state : started

- name: ctlabs_k8s.tasks.service.ingress.controller.ready
  vars:
    ansible_python_interpreter: /usr/sbin/ip vrf exec default /usr/bin/python3
  ansible.builtin.wait_for:
    host   : "{{ ansible_nodename }}"
    port   : 443
    state  : started
    timeout: 300 
    delay  : 10
