---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_base/defaults/main.yml
# Description : main defaults file
# ------------------------------------------------------------------------------

ar_plugin_redhat: "{{ 'yum-plugin-artifact-registry' if ctg_os_version == '7' else 'dnf-plugin-artifact-registry' }}"

# role defaults
ctlabs_base:
  defaults:
    repos:
      redhat:
        - name: ar-plugin
          desc: Artifact Registry Plugin
          type: main
          url : "https://packages.cloud.google.com/yum/repos/{{ ar_plugin_redhat }}-stable"
          key : |-
            https://packages.cloud.google.com/yum/doc/yum-key.gpg
            https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        - name : gcsfuse
          desc : Cloud Storage FUSE
          url  : "https://packages.cloud.google.com/yum/repos/gcsfuse-el7-x86_64"
          key  : |-
            https://packages.cloud.google.com/yum/doc/yum-key.gpg
            https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      debian: []
    keys:
      redhat:
        - url: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ctg_os_version }}"
      debian: []
    pkgs:
      redhat:
        - name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
          when: "{{ ctg_vendor == 'google' and ctg_os == 'redhat9' }}"
        - name: python3
        - name: python3-pip
        - name: python3-requests
        - name: "{{ ar_plugin_redhat }}"
        - name: epel-release
        - name: htop
        - name: sysstat
        - name: gcsfuse
        - name: podman-docker
        - name: nfs-utils
        - name: bpftrace
          when: "{{ (ctg_os_version|int) > 7 }}"
        - name: bpftool
        - name: bcc-tools
        - name: nmap-ncat
      debian:
        - name: gpg
        - name: htop
        - name: xfsprogs
        - name: apt-transport-artifact-registry
        - name: netcat-openbsd
      windows:
        - name: chocolatey
    scripts:
      windows:
        - name: psoptimize.ps1
    config:
      gce_disk_prefix: /dev/disk/by-id/google-
      local_facts:
        template: ctlabs_base_disks.fact.j2
        file    : /etc/ansible/facts.d/ctlabs_base_disks.fact
      profiled:
        - template: bashrc_kali.sh.j2
          file    : /etc/profile.d/bashrc_kali.sh
        - template: bashrc_ctlabs.j2
          file    : /etc/profile.d/bashrc_ctlabs.sh
      tmux:
        template: tmux.conf.j2
        file    : /etc/tmux.conf
      windows:
        local_facts:
          - file    : "{{ ctg_facts_dir }}/ctlabs.ps1"
            template: facts.ps1.j2
        profile:
          file    : C:/Windows/System32/WindowsPowerShell/v1.0/profile.ps1
          template: profile.ps1.j2
    sysconfig:
    service:
  os:
    - redhat7
    - redhat8
    - redhat9
    - centos7
    - centos8
    - centos9
    - debian11
    - debian12
    - microsoft windows server 2022 standard evaluation
  virtype:
    - kvm
    - vmware
