---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_metallb/handlers/main.yml
# Description : handlers
# ------------------------------------------------------------------------------
