---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_syslog/tasks/precheck.yml
# Description : prechecks
# ------------------------------------------------------------------------------

- name: ctlabs_syslog.tasks.precheck
  block:
    - name: ctlabs_syslog.tasks.precheck.os.supported
      assert:
        that: ctg_os is in ctlabs_syslog.os
        fail_msg: "{{ ctg_os }} is not supported!"
  rescue:
    - name: ctlabs_syslog.tasks.precheck.skip.unsupported
      meta: end_host

- name: ctlabs_syslog.tasks.precheck.default_type
  set_fact:
    ctlabs_syslog_kind: "{{ ctlabs_syslog_kind | default(ctlabs_syslog.kind) }}"

- name: ctlabs_syslog.tasks.precheck.default_type
  set_fact:
    ctlabs_syslog_kind: "{{ ctg_facts.ctlabs.syslog.kind | default(ctlabs_syslog.kind) }}"
  when: ctg_facts.ctlabs is defined and ctg_facts.ctlabs.syslog is defined and ctg_facts.ctlabs.syslog.kind is defined # and ctg_facts.ctlabs.syslog.kind is in ["syslog-ng", "rsyslog"]                                                                                     
