---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_openclaw/defaults/main.yml
# Description : main defaults
# ------------------------------------------------------------------------------

versions:

ctlabs_openclaw:
  defaults:
    pkgs:
      debian: 
        - name: curl
        - name: nodejs
        - name: npm
        - name: git
        - name: build-essential
        - name: python3-dev
      redhat: []
    script:
      url : https://openclaw.ai/install.sh
      path: /tmp/install.sh
    config:
      dir     : ~/.openclaw
      template: openclaw.json.j2
      file    : ~/.openclaw/openclaw.json
    service:
      name    : openclaw.service
      template: openclaw.service.j2
      file    : "{{ ctg_systemd_dir }}/openclaw.service"
  os:
    - debian12
    - kali2025
