---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_openclaw/defaults/main.yml
# Description : main defaults
# ------------------------------------------------------------------------------

versions:
  nodejs: node_22.x

ctlabs_openclaw:
  defaults:
    repos:
      debian:
        - name: nodesource
          url : "https://dev.nodesource.com/{{ versions.nodejs }}"
          key : https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    pkgs:
      debian: 
        - name: curl
        - name: nodejs
        - name: git
        - name: build-essential
        - name: python3-dev
      redhat: []
    config:
      repos:
        keydir: /etc/apt/keyrings
      dir     : /home/openclaw/.openclaw
      file    : /home/openclaw/.openclaw/openclaw.json
      template: openclaw.json.j2
    certs:
      dir: /etc/ca-ctlabs
      crt: "{{ ansible_nodename }}.crt"
      key: "{{ ansible_nodename }}.prv"
      ca:  ca.crt
    service:
      name    : openclaw.service
      template: openclaw.service.j2
      file    : "{{ ctg_systemd_dir }}/openclaw.service"
      user    : openclaw
      group   : openclaw
      groups  : [certs]
  os:
    - debian12
    - kali2025
